apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: my-vehicle-prod

commonLabels:
  environment: production

resources:
  - ../../base
  - namespace.yaml

patches:
  - target:
      kind: Namespace
      name: my-vehicle-dashboard
    patch: |
      $patch: delete
      apiVersion: v1
      kind: Namespace
      metadata:
        name: my-vehicle-dashboard
  - target:
      kind: Deployment
      name: my-vehicle-dashboard-backend
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "1Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "200m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "1000m"
  - target:
      kind: Deployment
      name: my-vehicle-dashboard-frontend
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "1Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "200m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "1000m"

images:
  - name: image-registry.openshift-image-registry.svc:5000/my-vehicle-dashboard/backend
    newName: image-registry.openshift-image-registry.svc:5000/my-vehicle-prod/backend
    newTag: latest
  - name: image-registry.openshift-image-registry.svc:5000/my-vehicle-dashboard/frontend
    newName: image-registry.openshift-image-registry.svc:5000/my-vehicle-prod/frontend
    newTag: latest

replicas:
  - name: my-vehicle-dashboard-backend
    count: 2
  - name: my-vehicle-dashboard-frontend
    count: 2
